import type { Artist, ShopTheme } from "./types";

export const DEMO_ARTISTS: Artist[] = [
  {
    slug: "alleged-arts",
    name: "Lisa Orth",
    pronouns: "she/her",
    studio: "Alleged Arts",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Private loft. Contemporary work. Quiet on purpose.",
    bio: "Queer womxn-owned studio in a converted automotive warehouse — soaring ceilings, vintage wood, natural light, curated soundtrack. Appointment-only. This demo replaces the DM → Venmo → PDF waiver scramble with one calm link before anyone climbs the stairs.",
    specialty: "Original contemporary tattoo art",
    tags: ["Private loft", "Queer-owned", "Guest artists welcome", "No walk-ins"],
    depositCents: 15000,
    hourlyRateCents: 25000,
    sessionNote: "Projects typically start at a half-day minimum",
    depositPolicy:
      "Deposit applies to your session total. Forfeited if you no-show or cancel inside 72 hours. Reschedules with 72+ hours notice keep the deposit on file.",
    instagram: "@allegedarts",
    email: "demo@inkhold.app",
    theme: "loft-calm",
    locationNote:
      "Arts loft complex, Capitol Hill — private entrance, not a street-level flash shop",
    form: {
      placementPlaceholder: "Where on the body — and any prior work nearby?",
      descriptionPlaceholder:
        "Describe the concept. Alleged books original contemporary work — not copies of another artist’s tattoos.",
      datesPlaceholder: "Weekday mornings preferred? Multi-session ok?",
      ctaLabel: "Hold the loft with a $150 deposit",
    },
    extraQuestion: {
      name: "priorWork",
      label: "Anything we should know about skin, pain tolerance, or accessibility?",
      placeholder: "ADA needs, sensory preferences, medical notes…",
    },
    salesHook:
      "Show Lisa/the studio: bio → deposit → waiver before the warehouse stairs.",
  },
  {
    slug: "sorry-sorry",
    name: "Raychelle Ordoñez",
    pronouns: "she/her",
    studio: "Sorry Sorry Tattoo",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Gold window. Neon TATTOO. Wave — we’ll unlock the door.",
    bio: "Illustrative, fully-shaded work from a queer-friendly Cap Hill storefront (est. 2021 by Angela & Raychelle). Grey face, three big windows, gold & white signage, white door with a code. Artists design the piece — they turn away “copy this IG tattoo” requests. This demo is the booking link you’d drop in the bio instead of “email the artist.”",
    specialty: "Illustrative · Color · Cultural & queer themes",
    tags: ["Locked door", "Illustrators first", "Queer-friendly", "1214 10th Ave"],
    depositCents: 10000,
    hourlyRateCents: 20000,
    sessionNote: "Book the artist, not the shop desk — Raychelle / Kat / Dayze / guests",
    depositPolicy:
      "Deposit holds your seat with your chosen artist. No-shows forfeit it. We design original work — bring inspiration, not someone else’s finished tattoo to clone.",
    instagram: "@sorrysorrytattoo",
    email: "demo@inkhold.app",
    theme: "neon-window",
    locationNote:
      "1214 10th Ave — across from Woodworth apartments, between Seneca & Union. Wave at the window.",
    form: {
      placementPlaceholder: "Placement + approximate size in inches",
      descriptionPlaceholder:
        "Subject, color vibes, cultural or personal meaning. We’ll adapt into an illustrative style — not a 1:1 of another tattoo.",
      datesPlaceholder: "Weekends vs weekdays? Flexible on month?",
      ctaLabel: "Pay $100 — we’ll unlock your slot",
    },
    extraQuestion: {
      name: "whichArtist",
      label: "Who are you hoping to sit with?",
      placeholder: "Raychelle, Kat, Dayze, guest, or “whoever fits the style”",
    },
    salesHook: "Pitch the locked-door chaos: deposit before anyone waves you in.",
  },
  {
    slug: "elevation-project",
    name: "Emma Grace Larkin",
    pronouns: "she/her",
    studio: "Elevation Project",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Tattoo studio · art gallery · creative loft on 11th.",
    bio: "Emma apprenticed in Istanbul, worked NYC/NJ, then opened Elevation as tattoo + gallery + event space at 1506 11th Ave. Signature blend: abstract, realism, watercolor collage. This demo is the appointment request that actually collects a deposit — not another form that dies in email.",
    specialty: "Abstract · Realism · Watercolor collage",
    tags: ["Gallery loft", "Founder-owned", "Events space", "1506 11th Ave"],
    depositCents: 12500,
    hourlyRateCents: 22000,
    sessionNote: "Collage / watercolor pieces often need consult + draw time",
    depositPolicy:
      "Deposit reserves Emma’s chair and draw time. Applied to the finished piece. Cancel 5+ days out to reschedule; inside that window the deposit is kept.",
    instagram: "@elevation_project",
    email: "demo@inkhold.app",
    theme: "gallery-bright",
    locationNote: "Bright loft gallery at 1506 11th Ave, Capitol Hill",
    form: {
      placementPlaceholder: "Body placement + how it should flow with existing work",
      descriptionPlaceholder:
        "Abstract / realism / watercolor direction? Mood references welcome — collage composition notes help.",
      datesPlaceholder: "Need evening sessions? Ok with multi-visit?",
      ctaLabel: "Reserve Emma’s chair — $125",
    },
    extraQuestion: {
      name: "galleryVisit",
      label: "Want to visit the gallery space before the session?",
      placeholder: "Yes / no / maybe — any event-night conflicts?",
    },
    salesHook: "Founder energy — show a link that matches the gallery brand.",
  },
  {
    slug: "facet-and-form",
    name: "Facet & Form Tattoo Desk",
    studio: "Facet and Form",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Unapologetic luxury. Gold, gems, and ink — same reverence.",
    bio: "Capitol Hill atelier at 1504 14th Ave. High-end piercing (BVLA) and custom tattoo in a moody, independent gallery — not a corporate neon box. Collective of tenured Cap Hill hands who left the mass-market model. This demo is hospitality-grade intake: deposit + waiver before the appointment feels cheap.",
    specialty: "Fine custom tattoo · Luxury piercing sibling",
    tags: ["Atelier", "1504 14th Ave", "BVLA piercing", "Hospitality-first"],
    depositCents: 20000,
    hourlyRateCents: 28000,
    sessionNote: "Custom tattoo consults treated like jewelry curation",
    depositPolicy:
      "Higher deposit reflects atelier booking standards. Applied to tattoo balance. No-show or same-week cancel forfeits deposit unless we rebook inside 30 days.",
    instagram: "@facetandform",
    email: "demo@inkhold.app",
    theme: "atelier-moody",
    locationNote: "1504 14th Ave — moody gallery lighting, intentional quiet",
    form: {
      placementPlaceholder: "Placement, visibility preference, jewelry adjacency?",
      descriptionPlaceholder:
        "What should this heirloom feel like? Line weight, negative space, longevity matters here.",
      datesPlaceholder: "Prefer midweek quiet hours?",
      ctaLabel: "Secure the atelier — $200 deposit",
    },
    extraQuestion: {
      name: "alsoPiercing",
      label: "Also booking piercing / gold curation the same visit?",
      placeholder: "Tattoo only / piercing same day / jewelry consult",
    },
    salesHook: "Luxury story — deposit flow should feel as curated as the space.",
  },
  {
    slug: "true-love",
    name: "True Love Artist Seat",
    studio: "True Love Tattoo",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Longest-running gay-owned shop on the Hill. Relaxed, not sloppy.",
    bio: "LGBTQIA-centric Capitol Hill staple — call/email for artist availability, Friday the 13th flash culture, rotating community energy. This demo isn’t “replace the front desk.” It’s the link for the artist who still says “Venmo me $100 and I’ll pencil you in.”",
    specialty: "Traditional · Custom · Community flash",
    tags: ["LGBTQIA-centric", "Gay-owned", "Flash days", "Artist-direct"],
    depositCents: 10000,
    hourlyRateCents: 18000,
    sessionNote: "Ask which artist — roster books separately",
    depositPolicy:
      "Deposit holds with your artist. Shop flash events may use different rules — this link is for custom appointment holds.",
    instagram: "@truelovetattoo",
    email: "demo@inkhold.app",
    theme: "queer-warm",
    locationNote: "Capitol Hill — relaxed queer community shop floor",
    form: {
      placementPlaceholder: "Spot + cover-up? (be honest)",
      descriptionPlaceholder:
        "Traditional, weird, sentimental — tell us the story. Name your preferred artist if you have one.",
      datesPlaceholder: "Avoiding Pride week? Friday the 13th flash instead?",
      ctaLabel: "Hold my artist — $100",
    },
    extraQuestion: {
      name: "artistPick",
      label: "Preferred artist (or “surprise me with who fits”)",
      placeholder: "Name or style match",
    },
    salesHook: "Sell the artist, not the desk — Venmo kids on the roster.",
  },
  {
    slug: "dark-age",
    name: "Dark Age Custom Desk",
    studio: "Dark Age Tattoo",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Classic Cap Hill shop. Walk-ins when it works. Customs when it’s real.",
    bio: "Street-level Capitol Hill shop with roster energy and Friday the 13th flash reputation. This page is only for custom appointment deposits — flash walk-ins stay walk-ins. Pitch it to whoever still texts clients “send deposit when you can.”",
    specialty: "Traditional · Blackwork · Custom appointments",
    tags: ["Walk-ins case-by-case", "Flash events", "Custom deposits"],
    depositCents: 10000,
    hourlyRateCents: 17500,
    sessionNote: "Custom projects book ahead; flash is a different lane",
    depositPolicy:
      "Custom appointment deposit only. Flash / Friday the 13th uses shop event rules — don’t use this link for those.",
    instagram: "@darkagetattoo",
    email: "demo@inkhold.app",
    theme: "classic-shop",
    locationNote: "Capitol Hill street shop — ask for the artist, not “whoever’s free” for customs",
    form: {
      placementPlaceholder: "Placement + any cover-up photos linked below",
      descriptionPlaceholder:
        "Custom concept only. If you want flash, walk in or watch for Friday the 13th — don’t book it here.",
      datesPlaceholder: "Earliest month that works?",
      ctaLabel: "Lock custom slot — $100",
    },
    salesHook: "Separate custom deposits from flash chaos.",
  },
  {
    slug: "supergenius",
    name: "Supergenius Artist",
    studio: "Supergenius Tattoo",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Established Cap Hill roster. Your bio link, not a shop OS takeover.",
    bio: "Known Capitol Hill studio with illustrative / neo-trad muscle. Demo for a single artist who wants clients to stop DMing mid-session. Shop keeps whatever desk system they like — this is the artist’s personal hold link.",
    specialty: "Illustrative · Neo-traditional · Custom",
    tags: ["Roster shop", "Artist-owned link", "Illustrative"],
    depositCents: 12500,
    hourlyRateCents: 20000,
    sessionNote: "Draw time billed into project or quoted up front",
    depositPolicy:
      "Deposit holds the artist’s calendar. Shop policies still apply for health & safety; this is the money + intake layer.",
    instagram: "@supergeniustattoo",
    email: "demo@inkhold.app",
    theme: "classic-shop",
    locationNote: "Capitol Hill — ask for your artist by name at the desk",
    form: {
      placementPlaceholder: "Placement, flow with existing work",
      descriptionPlaceholder:
        "Neo-trad / illustrative direction, color vs black, must-include motifs",
      datesPlaceholder: "Blocked travel dates?",
      ctaLabel: "Deposit $125 to my artist",
    },
    salesHook: "Wedge: one artist yes without ripping the shop stack.",
  },
  {
    slug: "laughing-buddha",
    name: "Laughing Buddha Artist",
    studio: "Laughing Buddha Tattoo",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Busy floor. Your deposit shouldn’t live in a group chat screenshot.",
    bio: "High-energy Cap Hill shop spanning American traditional, Japanese, and custom. Demo for the artist drowning in “did you Venmo yet?” texts while the shop hums. Not a front-desk replacement — a quiet money rail for customs.",
    specialty: "American traditional · Japanese · Custom",
    tags: ["Busy floor", "Multi-style roster", "Custom rail"],
    depositCents: 10000,
    hourlyRateCents: 18000,
    sessionNote: "Large Japanese / traditional projects may need mapped sessions",
    depositPolicy:
      "Deposit applies to custom work with your artist. Forfeited on no-show. Large projects may require a second deposit before session two.",
    instagram: "@laughingbuddhatattoo",
    email: "demo@inkhold.app",
    theme: "classic-shop",
    locationNote: "Capitol Hill — noisy shop floor, private consult via this link first",
    form: {
      placementPlaceholder: "Body area + existing irezumi / trad work nearby?",
      descriptionPlaceholder:
        "Trad flash energy or full custom Japanese plan? Be specific about scale.",
      datesPlaceholder: "Can you sit 4+ hours?",
      ctaLabel: "Send $100 deposit",
    },
    salesHook: "One roster artist’s Venmo pain is enough of a close.",
  },
  {
    slug: "seattle-tattoo-emporium",
    name: "Emporium Custom Desk",
    studio: "Seattle Tattoo Emporium",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "High volume up front. Customs still need a real hold.",
    bio: "Busy Cap Hill stop for flash and cover-ups. This page is intentionally strict: custom / cover-up appointments only. Walk-up flash stays at the counter. Deposit proves the client is serious before stencil day.",
    specialty: "Flash counter · Custom · Cover-ups",
    tags: ["High volume", "Cover-ups", "Custom-only link"],
    depositCents: 7500,
    hourlyRateCents: 15000,
    sessionNote: "Cover-ups need clear photos of existing work",
    depositPolicy:
      "Lower deposit, same seriousness. No-show = gone. Cover-up quotes may change after in-person look — deposit still holds the consult slot.",
    instagram: "@seattletattooemporium",
    email: "demo@inkhold.app",
    theme: "classic-shop",
    locationNote: "Capitol Hill — counter for flash; this link for booked customs",
    form: {
      placementPlaceholder: "Cover-up? Say what’s there now.",
      descriptionPlaceholder:
        "Custom or cover-up plan. Link photos of existing ink. Flash walk-ins don’t use this form.",
      datesPlaceholder: "Soonest week you can sit?",
      ctaLabel: "Hold consult — $75",
    },
    extraQuestion: {
      name: "coverUp",
      label: "Cover-up details",
      placeholder: "Age of tattoo, color vs black, how light/dark it is now",
    },
    salesHook: "Prove customs can be calm inside a loud shop.",
  },
  {
    slug: "hurricane-violet",
    name: "Hurricane Violet",
    pronouns: "she/her",
    studio: "Hurricane Violet Private Studio",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Bold neotrad. Private ADA studio. Pick the music. Control the AC.",
    bio: "Capitol Hill private studio — Mon/Wed/Fri + weekends; closed Tue/Thu. Not accepting walk-ins. Plants, animals, pop-culture, surrealism; black & grey or color. She already takes cash/card/Venmo and texts for booking. This demo is the upgrade: structured intake + deposit without the text-thread archaeology.",
    specialty: "Bold neotraditional · Illustrative · Color & B&G",
    tags: ["Private studio", "ADA-accessible", "No walk-ins", "Neotrad"],
    depositCents: 15000,
    hourlyRateCents: 22000,
    sessionNote: "Open Mon/Wed/Fri + weekends — closed Tue & Thu",
    depositPolicy:
      "Deposit holds the private studio block. Applied to the tattoo. No-shows forfeit. Reschedule with notice and it rolls forward.",
    instagram: "@hurricaneviolet",
    email: "demo@inkhold.app",
    theme: "indie-ink",
    locationNote: "Private Cap Hill studio — peaceful, ADA-accessible, you control the room",
    form: {
      placementPlaceholder: "Placement — room for bold neotrad frames?",
      descriptionPlaceholder:
        "Plants, animals, pop-culture, surreal? Color or black & grey? Must-have motifs.",
      datesPlaceholder: "Avoiding her closed Tue/Thu — which open days work?",
      ctaLabel: "Hold Violet’s studio — $150",
    },
    extraQuestion: {
      name: "musicAc",
      label: "Session vibe",
      placeholder: "Music genre + AC preference (she lets you run the room)",
    },
    salesHook: "Fastest close — already private + Venmo. Show the cleaner link.",
  },
  {
    slug: "wren-cavanaugh",
    name: "Wren Cavanaugh",
    pronouns: "they/them",
    studio: "Wren Cavanaugh Tattoos",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Etching, linocut, woodcut energy — black & grey flora, fauna, queer themes.",
    bio: "Capitol Hill artist into printmaking-adjacent line work: etching-style, linocut, woodcut black and gray. Flash + custom. Queer/gay themes, flora & fauna, fine-art feel. They already have a booking form — this demo shows what “form + real deposit + waiver” feels like in one pass.",
    specialty: "Etching / linocut / woodcut · B&G · Queer themes",
    tags: ["they/them", "Flash + custom", "Printmaking vibe", "Cap Hill"],
    depositCents: 12500,
    hourlyRateCents: 20000,
    sessionNote: "Flash books faster; custom needs draw time",
    depositPolicy:
      "Deposit required to hold custom or reserved flash. Check Wren’s pricing page for size tiers — this demo uses a flat hold for the pitch.",
    instagram: "@wrencavanaugh",
    email: "demo@inkhold.app",
    theme: "indie-ink",
    locationNote: "Capitol Hill — etching-style black & grey specialist",
    form: {
      placementPlaceholder: "Where should the print-like lines live?",
      descriptionPlaceholder:
        "Flash sheet piece or custom? Flora, fauna, queer/fine-art themes — describe the etching feel you want.",
      datesPlaceholder: "Flexible month? Need a consult first?",
      ctaLabel: "Book with Wren — $125 deposit",
    },
    extraQuestion: {
      name: "flashOrCustom",
      label: "Flash from the sheet, or custom drawing?",
      placeholder: "Flash name/number if known, or “custom”",
    },
    salesHook: "They have a form — show deposit+waiver as the missing piece.",
  },
  {
    slug: "central-district-studio",
    name: "Central Studio Artist",
    studio: "Central District Appointment Studio",
    neighborhood: "Central District",
    city: "Seattle",
    headline: "Queer-owned, appointment-only — portfolios first, then the hold.",
    bio: "Central District appointment culture: walk in to see the space, book the artist directly, rotating guests. Demo for the artist who wants deposits without turning the studio into a corporate booking widget.",
    specialty: "Illustrative · Ornamental · Guest rotations",
    tags: ["Queer-owned", "Appt only", "Guest artists", "Central District"],
    depositCents: 10000,
    hourlyRateCents: 19000,
    sessionNote: "Guest artist weeks may have separate deposit rules",
    depositPolicy:
      "Deposit holds resident artist time. Guest-artist bookings may use a separate link during their week.",
    instagram: "@seattleinkhold",
    email: "demo@inkhold.app",
    theme: "queer-warm",
    locationNote: "Central District — appointment-only; visit to view portfolios welcome",
    form: {
      placementPlaceholder: "Placement + ornamental flow notes",
      descriptionPlaceholder:
        "Illustrative / ornamental direction. Mention if you saw a guest’s work.",
      datesPlaceholder: "Around guest weeks or only residents?",
      ctaLabel: "Hold the appointment — $100",
    },
    salesHook: "Ask for intros to guest artists after a resident yes.",
  },
  {
    slug: "hidden-hand",
    name: "Hidden Hand Custom Desk",
    studio: "Hidden Hand Tattoo",
    neighborhood: "Fremont",
    city: "Seattle",
    headline: "Fremont cornerstone since 2007. Customs by default — flash on the wall.",
    bio: "Jeff & April Cornell’s shop — multi-style roster, mostly fully custom one-of-ones, plus flash for inspiration. Open daily energy with walk-ins when possible. This demo link is for custom appointment deposits, not the person grabbing a small flash off the wall today.",
    specialty: "Fully custom · Multi-style roster · Flash library",
    tags: ["Est. 2007", "Fremont", "Custom-first", "Walk-ins when free"],
    depositCents: 10000,
    hourlyRateCents: 17500,
    sessionNote: "Bodysuit / large custom planning available across the roster",
    depositPolicy:
      "Custom appointment deposit with your artist. Walk-in flash paid at the counter — don’t use this link for that.",
    instagram: "@hiddenhandtattoo",
    email: "demo@inkhold.app",
    theme: "fremont-flash",
    locationNote: "Fremont — cornerstone Seattle shop since June 2007",
    form: {
      placementPlaceholder: "Placement + long-term collection plans?",
      descriptionPlaceholder:
        "Fully custom concept. Styles across the roster — say who you’ve been watching.",
      datesPlaceholder: "Ok waiting for the right artist?",
      ctaLabel: "Custom hold — $100",
    },
    extraQuestion: {
      name: "artistWatching",
      label: "Which Hidden Hand artist’s page did you stalk?",
      placeholder: "Name or “match me”",
    },
    salesHook: "Lead with customs — skip Friday flash pitch.",
  },
  {
    slug: "crow-and-pitcher",
    name: "Emma Judd",
    pronouns: "she/her",
    studio: "Crow & Pitcher",
    neighborhood: "Fremont",
    city: "Seattle",
    headline: "One woman. One private Fremont studio. Illustration-rooted custom.",
    bio: "Emma Judd — sole artist/owner at 600 N 36th St. BIPOC / LGBTQIA+ / neurodivergent-friendly, female-owned, appointment-only. Color and black & grey; illustration background = adaptable styles. Hosts travelers sometimes, but day-to-day is Emma. This demo is the one-on-one booking hold that matches the private-room promise.",
    specialty: "Custom illustration-rooted · Color & B&G",
    tags: ["Female-owned", "Private", "600 N 36th", "Appt only"],
    depositCents: 15000,
    hourlyRateCents: 23000,
    sessionNote: "Collaborative private sessions — authenticity over speed",
    depositPolicy:
      "Deposit reserves Emma’s private studio day. Applied to the piece. Neurodivergent-friendly pacing — tell us what you need in the form.",
    instagram: "@crowandpitcher",
    email: "demo@inkhold.app",
    theme: "private-quiet",
    locationNote: "600 N 36th Street, Fremont — private studio, not a street flash shop",
    form: {
      placementPlaceholder: "Placement + comfort needs for a long private sit",
      descriptionPlaceholder:
        "Style range is wide — describe mood, color vs B&G, and what “done well” means to you.",
      datesPlaceholder: "Prefer mornings? Need breaks built in?",
      ctaLabel: "Reserve Emma’s room — $150",
    },
    extraQuestion: {
      name: "accessNeeds",
      label: "Access / sensory / neurodivergent needs",
      placeholder: "Lighting, breaks, communication style, anything else",
    },
    salesHook: "Private solo owner — bio link is the whole front office.",
  },
  {
    slug: "slave-to-the-needle",
    name: "Ballard Artist Seat",
    studio: "Slave to the Needle",
    neighborhood: "Ballard",
    city: "Seattle",
    headline: "Seattle institution — Ballard & Wallingford. Pick the artist, then hold them.",
    bio: "One of Seattle’s most recognized shops — Japanese to portraits to bodysuits, piercing at Ballard (508 NW 65th). Huge roster (Andrea, Bruce, Danny One-Shot, and more). This demo is deliberately one-artist-shaped: the question on the floor is “who still Venmos deposits?” — open their page, not a generic shop URL.",
    specialty: "Japanese · Realism · Custom large-scale",
    tags: ["Ballard + Wallingford", "Big roster", "Piercing @ Ballard"],
    depositCents: 10000,
    hourlyRateCents: 18000,
    sessionNote: "Large projects often multi-session across months",
    depositPolicy:
      "Deposit holds YOUR named artist at Ballard or Wallingford. Shop-wide policies still apply; this link doesn’t book “anyone free.”",
    instagram: "@slavetotheneedle",
    email: "demo@inkhold.app",
    theme: "ballard-trad",
    locationNote: "Ballard: 508 NW 65th · Wallingford: 403 NE 45th",
    form: {
      placementPlaceholder: "Bodysuit / sleeve / portrait placement",
      descriptionPlaceholder:
        "Japanese, realism, trad… and which STTN artist you want. Required.",
      datesPlaceholder: "Which location — Ballard or Wallingford?",
      ctaLabel: "Hold my STTN artist — $100",
    },
    extraQuestion: {
      name: "sttnArtist",
      label: "Artist name (required for this demo to make sense)",
      placeholder: "e.g. Julie Bolene, Justin Pino, Aaron Bell…",
    },
    salesHook: "Walk the floor: “Who still collects on Venmo?” → their link.",
  },
  {
    slug: "anchor-tattoo",
    name: "Anchor Artist",
    studio: "Anchor Tattoo",
    neighborhood: "Ballard",
    city: "Seattle",
    headline: "Small Ballard roster. Nautical soul. No enterprise bloat.",
    bio: "Tight Ballard shop — two-artist energy, traditional and nautical lean. Perfect InkHold wedge: too small for a full studio OS, too booked to chase Venmo. This page is the whole ops layer they’d actually use.",
    specialty: "Traditional · Nautical · Custom small-shop",
    tags: ["Small roster", "Ballard", "Nautical/trad"],
    depositCents: 10000,
    hourlyRateCents: 17000,
    sessionNote: "Small shop = limited weekly slots — deposit matters more",
    depositPolicy:
      "With only a couple chairs, no-shows hurt. Deposit forfeited on no-show; 48-hour reschedule keeps it.",
    instagram: "@anchortattooseattle",
    email: "demo@inkhold.app",
    theme: "harbor-small",
    locationNote: "Ballard — small shop, ask for your artist by name",
    form: {
      placementPlaceholder: "Arm, chest, calf — nautical flow?",
      descriptionPlaceholder:
        "Anchors, ships, trad motifs, or custom that still feels maritime?",
      datesPlaceholder: "Weekday afternoons easier?",
      ctaLabel: "Hold the chair — $100",
    },
    salesHook: "Tiny shop = instant “we don’t need Porter, we need this.”",
  },
  {
    slug: "rabid-hands",
    name: "Rabid Hands Artist",
    studio: "Rabid Hands Tattoo Studio",
    neighborhood: "Ballard",
    city: "Seattle",
    headline: "Traditional to illustrative. Appointments preferred. Pride flash with a cause.",
    bio: "Ballard studio spanning traditional → illustrative. Walk-ins if someone’s free; appointments preferred. Known for June Pride fundraiser flash supporting LGBTQ+ youth. This demo is the year-round custom hold — fundraiser days stay walk-in specials.",
    specialty: "Traditional · Illustrative",
    tags: ["Ballard", "Pride fundraiser", "Appts preferred"],
    depositCents: 10000,
    hourlyRateCents: 18000,
    sessionNote: "Pride flash weeks use event pricing — not this deposit link",
    depositPolicy:
      "Custom appointment deposit. Pride / benefit flash events are separate — pay at the event, don’t pre-pay here.",
    instagram: "@rabidhands",
    email: "demo@inkhold.app",
    theme: "ballard-trad",
    locationNote: "Ballard — appointments preferred; walk-ins if an artist is free",
    form: {
      placementPlaceholder: "Placement + trad vs illustrative lean",
      descriptionPlaceholder:
        "Custom piece description. If you want Pride flash, wait for June — don’t book it on this form.",
      datesPlaceholder: "Avoiding Pride week crowds?",
      ctaLabel: "Appointment deposit — $100",
    },
    salesHook: "Year-round customs vs benefit flash — different rails.",
  },
  {
    slug: "maya-rivera",
    name: "Maya Rivera",
    pronouns: "she/her",
    studio: "Blackpine Studio",
    neighborhood: "Capitol Hill",
    city: "Seattle",
    headline: "Generic product demo — fine-line botanicals, private chair.",
    bio: "Fictional profile for cold pitches when you’re not walking into a named shop. Use this when you need to show the product without leaning on a real studio’s brand.",
    specialty: "Fine-line · Botanicals · Blackwork",
    tags: ["Product demo", "Fictional", "Private"],
    depositCents: 10000,
    hourlyRateCents: 20000,
    sessionNote: "Demo artist — not a real bookable human",
    depositPolicy: "Demo policy: deposit applies to the fictional session total.",
    instagram: "@mayariveraink",
    email: "demo@inkhold.app",
    theme: "product-default",
    locationNote: "Fictional Cap Hill private studio for product demos",
    form: {
      placementPlaceholder: "e.g. outer forearm",
      descriptionPlaceholder: "Style, subject, color vs blackwork…",
      datesPlaceholder: "e.g. weekday evenings in August",
      ctaLabel: "Pay $100 deposit to hold",
    },
    salesHook: "Use when you need a neutral demo, not a named shop.",
  },
  {
    slug: "jordan-lee",
    name: "Jordan Lee",
    pronouns: "they/them",
    studio: "Needle & North",
    neighborhood: "Ballard",
    city: "Seattle",
    headline: "Generic Ballard product demo — neo-trad color.",
    bio: "Fictional Ballard artist for product walkthroughs. Prefer real shop pages when you’re on the street.",
    specialty: "Neo-traditional · Color",
    tags: ["Product demo", "Fictional", "Ballard"],
    depositCents: 15000,
    hourlyRateCents: 22000,
    sessionNote: "Demo only",
    depositPolicy: "Demo deposit policy for product screenshots.",
    instagram: "@jordanleetattoo",
    email: "demo@inkhold.app",
    theme: "product-default",
    locationNote: "Fictional Ballard studio",
    form: {
      placementPlaceholder: "e.g. upper arm",
      descriptionPlaceholder: "Animal / floral neo-trad ideas…",
      datesPlaceholder: "Weekends only?",
      ctaLabel: "Pay $150 deposit to hold",
    },
    salesHook: "Neutral Ballard-flavored product demo.",
  },
  {
    slug: "sam-okada",
    name: "Sam Okada",
    pronouns: "he/him",
    studio: "Okada Private",
    neighborhood: "Fremont",
    city: "Seattle",
    headline: "Generic Fremont private-studio product demo.",
    bio: "Fictional private studio profile. For real Fremont pitches use Crow & Pitcher or Hidden Hand pages.",
    specialty: "Japanese · Geometric",
    tags: ["Product demo", "Fictional", "Private"],
    depositCents: 12500,
    hourlyRateCents: 25000,
    sessionNote: "Demo only",
    depositPolicy: "Demo deposit — not a real studio policy.",
    instagram: "@samokada.ink",
    email: "demo@inkhold.app",
    theme: "product-default",
    locationNote: "Fictional Fremont private room",
    form: {
      placementPlaceholder: "e.g. forearm sleeve start",
      descriptionPlaceholder: "Japanese motifs, geometry, flow…",
      datesPlaceholder: "Month flexibility?",
      ctaLabel: "Pay $125 deposit to hold",
    },
    salesHook: "Neutral private-studio product demo.",
  },
];

export const NEIGHBORHOOD_ORDER = [
  "Capitol Hill",
  "Central District",
  "Fremont",
  "Ballard",
  "Seattle",
] as const;

export function getArtist(slug: string): Artist | undefined {
  return DEMO_ARTISTS.find((a) => a.slug === slug);
}

export function artistsByNeighborhood(): {
  neighborhood: string;
  artists: Artist[];
}[] {
  const map = new Map<string, Artist[]>();
  for (const artist of DEMO_ARTISTS) {
    const list = map.get(artist.neighborhood) ?? [];
    list.push(artist);
    map.set(artist.neighborhood, list);
  }
  const ordered: { neighborhood: string; artists: Artist[] }[] = [];
  for (const n of NEIGHBORHOOD_ORDER) {
    const artists = map.get(n);
    if (artists) ordered.push({ neighborhood: n, artists });
  }
  for (const [neighborhood, artists] of map) {
    if (!(NEIGHBORHOOD_ORDER as readonly string[]).includes(neighborhood)) {
      ordered.push({ neighborhood, artists });
    }
  }
  return ordered;
}

export function formatMoney(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(cents / 100);
}

export function themeLabel(theme: ShopTheme): string {
  return theme;
}
